# configs/artifacts.yaml
artifacts:
  base_path: "artifacts"
  models_path: "artifacts/models"
  metadata_path: "artifacts/metadata"
  reports_path: "artifacts/reports"
  monitoring_path: "artifacts/monitoring"
  input_file: "LD2011_2014.txt"
  output_file: "cleaned_data.csv"
